# Generated by Django 5.0.6 on 2024-07-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_orderdetail_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='customer_username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='stripe_payment_intent',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
